#!/bin/bash
#
# chkconfig: 2345 33 93
# description: check for user-data-env volumes, format, mount, add to fstab
#
## 6/18/12 - github.com/keen99
## run once on boot
##
## for EBS root volumes, resizes the root FS to fill the disk.
## 
## 

prog=$(basename $0)
logger="logger -s -t $prog"
curl="curl --retry 3 --silent --show-error --fail"
instance_data_url=http://169.254.169.254/2008-02-01

# Wait until meta-data is available.
$logger "waiting for meta-data..."
perl -MIO::Socket::INET -e '
 until(new IO::Socket::INET("169.254.169.254:80")){print"Waiting for meta-data...\n";sleep 1}
' | $logger

# Exit if we have already run on this instance (e.g., previous boot).
ami_id=$($curl $instance_data_url/meta-data/ami-id)
been_run_file=/var/ec2/$prog.$ami_id
mkdir -p $(dirname $been_run_file)
if [ -f $been_run_file ]; then
  $logger < $been_run_file
  exit
fi

##note that we COULD use a user-data hook to not rely on network and meta-data, but this should be more flexible

#if we're ephemeral:
#curl -s http://169.254.169.254/2008-02-01/meta-data/ami-manifest-path;echo
#easod-ami/easod-centos-5.4-x86_64-2.6.21-7v1.3-20110119-base-ami.manifest.xml
#
#if we're EBS
#curl -s http://169.254.169.254/2008-02-01/meta-data/ami-manifest-path;echo
#(unknown)

if [[ "$($curl $instance_data_url/meta-data/ami-manifest-path)" =~ unknown ]]
 then
	rootdevice=$($curl $instance_data_url/meta-data/block-device-mapping/root)
	if [[ "$rootdevice" =~ /dev/ ]]
	 then
		if [ -b $rootdevice ] 
		 then
			$logger "EBS root device, resizing root filesystem on $rootdevice"
			$logger "START: $(date)"
		else
			$logger "Couldn't find block device - $rootdevice"
			exit 1
		fi

		time -p resize2fs $rootdevice
		exit=$?
		if [ $exit -gt 0 ]
		 then
			$logger "resize2fs for $rootdevice failed, exit $exit"
			exit $exit
		else
			$logger "resize for $rootdevice complete"
			$logger "EDN: $(date)"
			exit 0
		fi
	else
		$logger "Failed to get root device from meta-data - $rootdevice"
		exit 1
	fi


else
	$logger "Emphemeral root device, not resizing"
	exit 0
fi
	
